/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.TreatmentDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.TreatmentModel;
import dao.AppointmentTreatmentDAO;
import model.AppointmentTreatmentModel;

/**
 *
 * @author DELL
 */
public class AddTreatment extends javax.swing.JFrame {
    
    private int appointmentNo;

    private ArrayList<TreatmentModel> treatmentList;

   
    public AddTreatment(int appointmentNo) {

    initComponents();

    setLocationRelativeTo(null);

    
    this.appointmentNo = appointmentNo;

    lblAppointmentNo.setText(
            "Appointment No: " + this.appointmentNo
    );

    txtAmount.setEditable(false);

    loadTreatments();
}
    private void loadTreatments() {

    cmbTreatment.removeAllItems();

    cmbTreatment.addItem("Select Treatment");

    TreatmentDAO dao = new TreatmentDAO();

    treatmentList = dao.getAllTreatments();
    

    for (TreatmentModel treatment : treatmentList) {

        cmbTreatment.addItem(
                treatment.getTreatmentName()
        );
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblAppointmentNo = new javax.swing.JLabel();
        cmbTreatment = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnAddTreatment = new javax.swing.JButton();
        btnViewTreatments = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Appointment NO.");

        lblAppointmentNo.setText("jLabel2");

        cmbTreatment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTreatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTreatmentActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Treatment Type");

        txtAmount.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Amount");

        btnAddTreatment.setBackground(new java.awt.Color(0, 0, 204));
        btnAddTreatment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddTreatment.setForeground(new java.awt.Color(255, 255, 255));
        btnAddTreatment.setText("Add Treatment");
        btnAddTreatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTreatmentActionPerformed(evt);
            }
        });

        btnViewTreatments.setBackground(new java.awt.Color(0, 51, 204));
        btnViewTreatments.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnViewTreatments.setForeground(new java.awt.Color(255, 255, 255));
        btnViewTreatments.setText("View Add Treatment");
        btnViewTreatments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTreatmentsActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 0, 204));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbTreatment, 0, 170, Short.MAX_VALUE)
                    .addComponent(txtAmount)
                    .addComponent(lblAppointmentNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(159, 159, 159))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnAddTreatment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnViewTreatments)
                .addGap(49, 49, 49)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblAppointmentNo))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddTreatment)
                    .addComponent(btnViewTreatments)
                    .addComponent(btnBack))
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTreatmentActionPerformed
        // TODO add your handling code here:
         int index = cmbTreatment.getSelectedIndex();

    if (index <= 0 || treatmentList == null) {

        txtAmount.setText("");

        return;
    }

    TreatmentModel treatment =
            treatmentList.get(index - 1);

    txtAmount.setText(
            String.valueOf(treatment.getAmount())
    );
    }//GEN-LAST:event_cmbTreatmentActionPerformed

    private void btnAddTreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTreatmentActionPerformed
       
         int index = cmbTreatment.getSelectedIndex();

    if (index <= 0) {

        JOptionPane.showMessageDialog(this,
                "Please select a treatment.");

        return;
    }

    TreatmentModel selectedTreatment =
            treatmentList.get(index - 1);

    AppointmentTreatmentModel appointmentTreatment =
            new AppointmentTreatmentModel();

    appointmentTreatment.setAppointmentNo(
            appointmentNo
    );

    appointmentTreatment.setTreatmentId(
            selectedTreatment.getTreatmentId()
    );

    appointmentTreatment.setTreatmentName(
            selectedTreatment.getTreatmentName()
    );

    appointmentTreatment.setAmount(
            selectedTreatment.getAmount()
    );

    AppointmentTreatmentDAO dao =
            new AppointmentTreatmentDAO();
    
    if (dao.treatmentAlreadyAdded(
        appointmentNo,
        selectedTreatment.getTreatmentId())) {

    JOptionPane.showMessageDialog(this,
            "This treatment has already been added.");

    return;
}
    boolean result =
            dao.addAppointmentTreatment(
                    appointmentTreatment
            );

    if (result) {

        JOptionPane.showMessageDialog(this,
                "Treatment added successfully!\n"
                + "Treatment: "
                + selectedTreatment.getTreatmentName()
                + "\nAmount: Rs. "
                + selectedTreatment.getAmount()
        );

        cmbTreatment.setSelectedIndex(0);
        txtAmount.setText("");

    } else {

        JOptionPane.showMessageDialog(this,
                "Failed to add treatment.");
    }
    }//GEN-LAST:event_btnAddTreatmentActionPerformed

    private void btnViewTreatmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTreatmentsActionPerformed
        // TODO add your handling code here:
          new ViewAppointmentTreatments(
            appointmentNo
          ).setVisible(true);

            this.dispose();
    }//GEN-LAST:event_btnViewTreatmentsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        DoctorDashboard dashboard = new DoctorDashboard();
        dashboard.openTab(1);
        dashboard.setVisible(true);

this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTreatment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTreatment(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTreatment;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewTreatments;
    private javax.swing.JComboBox<String> cmbTreatment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAppointmentNo;
    private javax.swing.JTextField txtAmount;
    // End of variables declaration//GEN-END:variables

    private void print_r(ArrayList<TreatmentModel> treatmentList) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
