/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.AppointmentDAO;
import dao.AppointmentTreatmentDAO;
import dao.BillDAO;
import dao.UserDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.UserModel;
import session.Session;
import javax.swing.table.DefaultTableModel;
import model.AppointmentTreatmentModel;
import model.AppointmentModel;
import model.BillModel;

import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;

/**
 *
 * @author DELL
 */
public class StaffDashBoard extends javax.swing.JFrame {
    
    private ArrayList<UserModel> doctorList;
    private int billAppointmentNo = 0;   
    private int billPatientId = 0;
    private double paymentAmount = 0.0;
    private double balanceAmount = 0.0;
    private String paymentStatus = "";
    private double treatmentTotal = 0.0;
    private double consultationFee = 1000.0;
    private double grandTotal = 0.0;

    /**
     * Creates new form StaffDashBoard
     */
    public StaffDashBoard() {
        initComponents();
        loadHelp();
        setLocationRelativeTo(null);
        txtAppointmentNo.setEditable(false);
        txtPatientName.setEditable(false);
        txtContactNum.setEditable(false);

        loadDoctors();
        loadAppointments();

        lblWelcome.setText(
            "Welcome, " + Session.getName()
    );
        
        jTabbedPane1.setUI(new javax.swing.plaf.basic.BasicTabbedPaneUI() {
        @Override
        protected int calculateTabAreaHeight(int tabPlacement, int horizRunCount, int maxTabHeight) {
            return 0;
        }
    });
        
    }
    
    private void loadHelp() {

    txtHelp.setText(
        "STAFF DASHBOARD HELP\n\n"

        + "1. Use the Appointment Management section to view appointments.\n\n"
        + "2. Search for an appointment using the Appointment Number.\n\n"
        + "3. Select an appointment from the table.\n\n"
        + "4. Staff can approve or reject appointments.\n\n"
        + "5. Add or update the appointment time when necessary.\n\n"
        + "6. Update appointment details if changes are required.\n\n"
        + "7. Delete incorrect or unwanted appointments carefully.\n\n"
        + "8. Use the Billing section to search for an appointment.\n\n"
        + "9. Calculate the treatment total and consultation fee.\n\n"
        + "10. Enter the payment amount and calculate the balance.\n\n"
        + "11. Save the bill after checking all details.\n\n"
        + "12. Print the bill or receipt for the patient.\n\n"
        + "13. Click Logout to safely leave the system."
    );
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnManageAppointments = new javax.swing.JButton();
        btnCreateBill = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtSearchAppointmentNo = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        txtAppointmentNo = new javax.swing.JTextField();
        txtPatientName = new javax.swing.JTextField();
        txtContactNum = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        cmbDentist = new javax.swing.JComboBox<>();
        txtDate = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAppointments = new javax.swing.JTable();
        jPanelBilling = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtBillAppointmentNo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lblBillPatientID = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBillTreatments = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        lblTreatmentTotal = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblConsultationFee = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblGrandTotal = new javax.swing.JLabel();
        txtPayment = new javax.swing.JTextField();
        btnCalculateBalance = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        btnSearchbill = new javax.swing.JButton();
        btnSaveBill = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        lblReceiptBillId = new javax.swing.JLabel();
        lblReceiptAppointmentNo = new javax.swing.JLabel();
        lblReceiptPatientId = new javax.swing.JLabel();
        lblReceiptTreatmentTotal = new javax.swing.JLabel();
        lblReceiptConsultationFee = new javax.swing.JLabel();
        lblReceiptGrandTotal = new javax.swing.JLabel();
        lblReceiptPayment = new javax.swing.JLabel();
        lblReceiptBalance = new javax.swing.JLabel();
        lblReceiptStatus = new javax.swing.JLabel();
        lblReceiptDate = new javax.swing.JLabel();
        btnPrintReceipt = new javax.swing.JButton();
        btnBackToBilling = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanelHelp = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtHelp = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        jButton1.setBackground(new java.awt.Color(51, 0, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnManageAppointments.setBackground(new java.awt.Color(51, 0, 204));
        btnManageAppointments.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManageAppointments.setForeground(new java.awt.Color(255, 255, 255));
        btnManageAppointments.setText("Manage Appointment");
        btnManageAppointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAppointmentsActionPerformed(evt);
            }
        });

        btnCreateBill.setBackground(new java.awt.Color(51, 0, 204));
        btnCreateBill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreateBill.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateBill.setText("Bill");
        btnCreateBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateBillActionPerformed(evt);
            }
        });

        btnHelp.setBackground(new java.awt.Color(51, 0, 204));
        btnHelp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHelp.setForeground(new java.awt.Color(255, 255, 255));
        btnHelp.setText("Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(51, 0, 204));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManageAppointments, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(btnCreateBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCreateBill, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel3.setBackground(new java.awt.Color(102, 255, 102));

        jPanel4.setBackground(new java.awt.Color(51, 204, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Patient Registration");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Email");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Contact Number");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Password");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Confirm Password");

        txtContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactKeyTyped(evt);
            }
        });

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        btnRegister.setBackground(new java.awt.Color(0, 102, 0));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(51, 255, 204));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(0, 0, 255));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConfirmPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btnClear)
                    .addComponent(btnLogin))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel3);

        jPanel5.setBackground(new java.awt.Color(51, 255, 102));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Appointment Number");

        txtSearchAppointmentNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchAppointmentNoActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(0, 153, 102));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(255, 255, 0));
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        txtContactNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNumActionPerformed(evt);
            }
        });

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        cmbDentist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Approved", "Rejected" }));

        btnUpdate.setBackground(new java.awt.Color(0, 0, 255));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(204, 0, 0));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(153, 255, 102));

        tblAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Appointment No", "Patient Name", "Contact Number", "Address", "Dentist", "Date", "Time", "Status"
            }
        ));
        tblAppointments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAppointmentsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblAppointments);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txtSearchAppointmentNo, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addGap(18, 18, 18)
                .addComponent(btnRefresh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAppointmentNo)
                            .addComponent(txtPatientName)
                            .addComponent(txtContactNum)
                            .addComponent(jScrollPane1)
                            .addComponent(cmbDentist, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDate)
                            .addComponent(txtTime)
                            .addComponent(cmbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSearchAppointmentNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(btnRefresh))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtAppointmentNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtContactNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbDentist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("tab3", jPanel5);

        jPanelBilling.setBackground(new java.awt.Color(51, 255, 102));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Appointment No:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Patient ID:");

        lblBillPatientID.setText("-");

        tblBillTreatments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Treatment ID", "Treatment Name", "Amount"
            }
        ));
        jScrollPane3.setViewportView(tblBillTreatments);
        if (tblBillTreatments.getColumnModel().getColumnCount() > 0) {
            tblBillTreatments.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Treatment Total:");

        lblTreatmentTotal.setText("-");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Consultation Fee:");

        lblConsultationFee.setText("-");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Grand Total:");

        lblGrandTotal.setText("-");

        txtPayment.setText("-");

        btnCalculateBalance.setBackground(new java.awt.Color(102, 255, 204));
        btnCalculateBalance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCalculateBalance.setText("Calculate Balance");
        btnCalculateBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateBalanceActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Balance:");

        lblBalance.setText("-");

        btnSearchbill.setBackground(new java.awt.Color(0, 0, 255));
        btnSearchbill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearchbill.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchbill.setText("Search");
        btnSearchbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchbillActionPerformed(evt);
            }
        });

        btnSaveBill.setBackground(new java.awt.Color(51, 0, 204));
        btnSaveBill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSaveBill.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveBill.setText("Save Bill");
        btnSaveBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBillingLayout = new javax.swing.GroupLayout(jPanelBilling);
        jPanelBilling.setLayout(jPanelBillingLayout);
        jPanelBillingLayout.setHorizontalGroup(
            jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBillingLayout.createSequentialGroup()
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBillingLayout.createSequentialGroup()
                        .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBillingLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBillingLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(70, 70, 70)
                        .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtBillAppointmentNo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblBillPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblTreatmentTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblConsultationFee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelBillingLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnSaveBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCalculateBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))))
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBillingLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnSearchbill, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBillingLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanelBillingLayout.setVerticalGroup(
            jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBillingLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBillAppointmentNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearchbill))
                    .addComponent(jLabel8))
                .addGap(46, 46, 46)
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblBillPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBillingLayout.createSequentialGroup()
                        .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lblTreatmentTotal))
                        .addGap(29, 29, 29)
                        .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(lblConsultationFee))
                        .addGap(29, 29, 29)
                        .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(lblGrandTotal)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(txtPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelBillingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBillingLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel16))
                    .addGroup(jPanelBillingLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnCalculateBalance)
                        .addGap(20, 20, 20)
                        .addComponent(lblBalance)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnSaveBill)
                .addGap(14, 14, 14))
        );

        jTabbedPane1.addTab("tab4", jPanelBilling);

        jPanel7.setBackground(new java.awt.Color(51, 255, 102));

        lblReceiptBillId.setText("jLabel9");

        lblReceiptAppointmentNo.setText("jLabel11");

        lblReceiptPatientId.setText("jLabel12");

        lblReceiptTreatmentTotal.setText("jLabel17");

        lblReceiptConsultationFee.setText("jLabel18");

        lblReceiptGrandTotal.setText("jLabel19");

        lblReceiptPayment.setText("jLabel20");

        lblReceiptBalance.setText("jLabel21");

        lblReceiptStatus.setText("jLabel22");

        lblReceiptDate.setText("jLabel23");

        btnPrintReceipt.setBackground(new java.awt.Color(0, 0, 204));
        btnPrintReceipt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPrintReceipt.setForeground(new java.awt.Color(255, 255, 255));
        btnPrintReceipt.setText("Print Receipt");
        btnPrintReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintReceiptActionPerformed(evt);
            }
        });

        btnBackToBilling.setBackground(new java.awt.Color(51, 0, 204));
        btnBackToBilling.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBackToBilling.setForeground(new java.awt.Color(255, 255, 255));
        btnBackToBilling.setText("Back  to Bill");
        btnBackToBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToBillingActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Bill ID");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Appointment No");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Patient ID");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Treatment Total");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Consultation Fee");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Grand Total");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Payment");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Balance");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Status");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Date");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(113, 113, 113)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblReceiptBillId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblReceiptAppointmentNo, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(lblReceiptPatientId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblReceiptTreatmentTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblReceiptConsultationFee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblReceiptGrandTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblReceiptPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblReceiptBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblReceiptStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblReceiptDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnPrintReceipt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBackToBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(404, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReceiptBillId)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReceiptAppointmentNo)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReceiptPatientId)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReceiptTreatmentTotal)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReceiptConsultationFee)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReceiptGrandTotal)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReceiptPayment)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReceiptBalance)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReceiptStatus)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReceiptDate)
                    .addComponent(jLabel23))
                .addGap(48, 48, 48)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrintReceipt)
                    .addComponent(btnBackToBilling))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab5", jPanel7);

        jPanelHelp.setBackground(new java.awt.Color(51, 255, 51));

        txtHelp.setColumns(20);
        txtHelp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtHelp.setRows(5);
        jScrollPane4.setViewportView(txtHelp);

        javax.swing.GroupLayout jPanelHelpLayout = new javax.swing.GroupLayout(jPanelHelp);
        jPanelHelp.setLayout(jPanelHelpLayout);
        jPanelHelpLayout.setHorizontalGroup(
            jPanelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHelpLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanelHelpLayout.setVerticalGroup(
            jPanelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHelpLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab5", jPanelHelp);

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblWelcome.setText("jLabel7");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblWelcome)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        String name = txtName.getText().trim();
String email = txtEmail.getText().trim();
String contact = txtContact.getText().trim();

String password = new String(txtPassword.getPassword());
String confirmPassword = new String(txtConfirmPassword.getPassword());

if (name.isEmpty()
        || email.isEmpty()
        || contact.isEmpty()
        || password.isEmpty()
        || confirmPassword.isEmpty()) {

    JOptionPane.showMessageDialog(this,
            "Please fill in all fields.");

    return;
}

if (!name.matches("[A-Za-z ]+")) {

    JOptionPane.showMessageDialog(this,
            "Name can contain letters and spaces only.");

    return;
}

String nameWithoutSpaces = name.replaceAll("\\s+", "");

if (nameWithoutSpaces.length() < 3) {

    JOptionPane.showMessageDialog(this,
            "Name must contain at least 3 letters.");

    return;
}

String emailPattern =
        "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";

if (!email.matches(emailPattern)) {

    JOptionPane.showMessageDialog(this,
            "Please enter a valid email address.");

    return;
}

if (!contact.matches("\\d{10}")) {

    JOptionPane.showMessageDialog(this,  "Contact number must contain exactly 10 digits.");
    return;
}

if (password.length() < 8) {

    JOptionPane.showMessageDialog(this, "Password must contain at least 8 characters.");
    return;
}

if (!password.equals(confirmPassword)) {

    JOptionPane.showMessageDialog(this,  "Password and Confirm Password do not match.");
    return;
}

UserModel user = new UserModel();

user.setName(name);
user.setEmail(email);
user.setContactNo(contact);
user.setRole("Patient");
user.setPassword(password);

UserDAO dao = new UserDAO();

boolean result = dao.registerUser(user);

if (result) {

    JOptionPane.showMessageDialog(this,  "Registration successful!");
    clearFields();



} else {

    JOptionPane.showMessageDialog(this,
            "Registration failed. Email may already exist.");
}
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();

    if (!Character.isDigit(c)
            || txtContact.getText().length() >= 10) {
        evt.consume();
    }
    }//GEN-LAST:event_txtContactKeyTyped

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION
    );

    if (choice == JOptionPane.YES_OPTION) {
        Session.clearSession();
        new Login().setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void txtSearchAppointmentNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchAppointmentNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchAppointmentNoActionPerformed

    private void txtContactNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNumActionPerformed

    private void tblAppointmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAppointmentsMouseClicked
        // TODO add your handling code here:
        int row = tblAppointments.getSelectedRow();

    if (row == -1) {
        return;
    }
    txtAppointmentNo.setText(
            tblAppointments.getValueAt(row, 0).toString()
    );
    txtPatientName.setText(
            tblAppointments.getValueAt(row, 1).toString()
    );
    txtContactNum.setText(
            tblAppointments.getValueAt(row, 2).toString()
    );
    txtAddress.setText(
            tblAppointments.getValueAt(row, 3).toString()
    );
    String dentist =
            tblAppointments.getValueAt(row, 4).toString();
    cmbDentist.setSelectedItem(dentist);
    txtDate.setText(
            tblAppointments.getValueAt(row, 5).toString()
    );
    Object timeValue =
            tblAppointments.getValueAt(row, 6);
    if (timeValue != null) {
        txtTime.setText(timeValue.toString());
    } else {
        txtTime.setText("");
    }
    cmbStatus.setSelectedItem(
            tblAppointments.getValueAt(row, 7).toString()
    );
    }//GEN-LAST:event_tblAppointmentsMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
         String search =
            txtSearchAppointmentNo.getText().trim();

    if (search.isEmpty()) {

        JOptionPane.showMessageDialog(this, "Please enter an appointment number.");
        return;
    }

    try {

        int appointmentNo =
                Integer.parseInt(search);

        AppointmentDAO dao =
                new AppointmentDAO();

        AppointmentModel appointment =
                dao.searchAppointment(appointmentNo);

        if (appointment == null) {

            JOptionPane.showMessageDialog(this, "Appointment not found.");
            return;
        }

        displayAppointment(appointment);

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(this,
                "Appointment number must contain numbers only.");
    }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (txtAppointmentNo.getText().isEmpty()) {

        JOptionPane.showMessageDialog(this, "Please select an appointment first.");

        return;
    }

    String address = txtAddress.getText().trim();
    String date = txtDate.getText().trim();
    String time = txtTime.getText().trim();
    String status =
            cmbStatus.getSelectedItem().toString();
    int selectedIndex =
            cmbDentist.getSelectedIndex();
    if (address.isEmpty()
            || date.isEmpty()
            || selectedIndex <= 0) {

        JOptionPane.showMessageDialog(this, "Please fill in all required fields.");
        return;
    }
    UserModel doctor =
            doctorList.get(selectedIndex - 1);
    int appointmentNo =
            Integer.parseInt(
                    txtAppointmentNo.getText()
            );

    AppointmentModel appointment =
            new AppointmentModel();

    appointment.setAppointmentNo(appointmentNo);
    appointment.setAddress(address);
    appointment.setDentistId(doctor.getUserId());
    appointment.setAppointmentDate(date);
    appointment.setAppointmentTime(time);
    appointment.setStatus(status);

    AppointmentDAO dao =
            new AppointmentDAO();

    boolean result =
            dao.updateAppointment(appointment);

    if (result) {

        JOptionPane.showMessageDialog(this,
                "Appointment updated successfully.");

        loadAppointments();

        clearFields();

    } else {

        JOptionPane.showMessageDialog(this,
                "Appointment update failed.");
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (txtAppointmentNo.getText().isEmpty()) {

        JOptionPane.showMessageDialog(this,
                "Please select an appointment first.");

        return;
    }

    int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this appointment?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
    );

    if (choice != JOptionPane.YES_OPTION) {

        return;
    }

    int appointmentNo =
            Integer.parseInt(
                    txtAppointmentNo.getText()
            );

    AppointmentDAO dao =
            new AppointmentDAO();

    boolean result =
            dao.deleteAppointment(appointmentNo);

    if (result) {

        JOptionPane.showMessageDialog(this,
                "Appointment deleted successfully.");

        loadAppointments();

        clearFields();

    } else {

        JOptionPane.showMessageDialog(this,
                "Appointment deletion failed.");
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnManageAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAppointmentsActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnManageAppointmentsActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
            loadAppointments();

            clearFields();

            JOptionPane.showMessageDialog(this,
            "Appointment list refreshed.");
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnCreateBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateBillActionPerformed
        
       clearBillingForm();
       jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnCreateBillActionPerformed

    private void btnSearchbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchbillActionPerformed
         String appointmentText =
            txtBillAppointmentNo.getText().trim();

    if (appointmentText.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter an appointment number.",
                "Input Required",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    try {

        billAppointmentNo =
                Integer.parseInt(appointmentText);

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Appointment number must contain numbers only.",
                "Invalid Appointment Number",
                JOptionPane.ERROR_MESSAGE
        );

        return;
    }

    loadBillAppointmentDetails();
    }//GEN-LAST:event_btnSearchbillActionPerformed

    private void btnCalculateBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateBalanceActionPerformed
          if (billAppointmentNo <= 0) {

        JOptionPane.showMessageDialog(
                this,
                "Please search for an appointment first.",
                "Appointment Required",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    String paymentText =
            txtPayment.getText().trim();

    if (paymentText.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter the payment amount.",
                "Payment Required",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

      try {

        paymentAmount =
                Double.parseDouble(paymentText);

        if (paymentAmount < 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Payment cannot be negative.",
                    "Invalid Payment",
                    JOptionPane.ERROR_MESSAGE
            );

            return;
        }

        if (paymentAmount >= grandTotal) {

            balanceAmount =
                    paymentAmount - grandTotal;

            paymentStatus = "Paid";

            lblBalance.setText(
                    "Change: Rs. "
                    + String.format(
                            "%.2f",
                            balanceAmount
                    )
            );

            JOptionPane.showMessageDialog(
                    this,
                    "Payment received successfully.\n"
                    + "Change: Rs. "
                    + String.format(
                            "%.2f",
                            balanceAmount
                    ),
                    "Payment Successful",
                    JOptionPane.INFORMATION_MESSAGE
            );

        } else {

            balanceAmount =
                    grandTotal - paymentAmount;

            paymentStatus = "Pending";

            lblBalance.setText(
                    "Remaining: Rs. "
                    + String.format(
                            "%.2f",
                            balanceAmount
                    )
            );

            JOptionPane.showMessageDialog(
                    this,
                    "Payment is incomplete.\n"
                    + "Remaining Amount: Rs. "
                    + String.format(
                            "%.2f",
                            balanceAmount
                    ),
                    "Payment Pending",
                    JOptionPane.WARNING_MESSAGE
            );
        }

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter a valid number.",
                "Invalid Payment",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnCalculateBalanceActionPerformed

    private void btnSaveBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveBillActionPerformed
       if (billAppointmentNo <= 0) {

        JOptionPane.showMessageDialog(
                this,
                "Please search for an appointment first."
        );

        return;
    }

    
    if (billPatientId <= 0) {

        JOptionPane.showMessageDialog(
                this,
                "Patient ID was not found."
        );

        return;
    }

   
    if (txtPayment.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter and calculate the payment first."
        );

        return;
    }
    
    
    BillDAO dao = new BillDAO();
    if (dao.billExists(billAppointmentNo)) {

        JOptionPane.showMessageDialog(
                this,
                "A bill already exists for this appointment.",
                "Duplicate Bill",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }
   
    BillModel bill =
            new BillModel();
    bill.setAppointmentNo(
            billAppointmentNo
    );
    bill.setPatientId(
            billPatientId
    );
    bill.setTreatmentTotal(
            treatmentTotal
    );
    bill.setConsultationFee(
            consultationFee
    );
    bill.setGrandTotal(
            grandTotal
    );
    bill.setPayment(
            paymentAmount
    );
    bill.setBalance(
            balanceAmount
    );
    bill.setPaymentStatus(
            paymentStatus
    );
    boolean result =
            dao.createBill(bill);

    if (result) {

        JOptionPane.showMessageDialog(
                this,
                "Bill saved successfully!"
        );

    } else {

        JOptionPane.showMessageDialog(
                this,
                "Failed to save bill."
        );
    }
    
    loadReceipt(billAppointmentNo);
    jTabbedPane1.setSelectedIndex(3);
    
    }//GEN-LAST:event_btnSaveBillActionPerformed

    private void btnBackToBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToBillingActionPerformed
         jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_btnBackToBillingActionPerformed

    private void btnPrintReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintReceiptActionPerformed
         if (billAppointmentNo <= 0) {

        JOptionPane.showMessageDialog(
                this,
                "Please select an appointment first.",
                "Bill Error",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    BillDAO billDAO = new BillDAO();

    BillModel bill =
            billDAO.getBillByAppointmentNo(
                    billAppointmentNo
            );

    if (bill == null) {

        JOptionPane.showMessageDialog(
                this,
                "Bill not found.\nPlease save the bill first.",
                "Bill Not Found",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    JFileChooser fileChooser =
            new JFileChooser();

    fileChooser.setDialogTitle(
            "Save Sunrise Dental Clinic Bill"
    );

    fileChooser.setSelectedFile(
            new File(
                    "Sunrise_Dental_Bill_"
                    + bill.getAppointmentNo()
                    + ".pdf"
            )
    );

    int result =
            fileChooser.showSaveDialog(this);

    if (result != JFileChooser.APPROVE_OPTION) {

        return;
    }

    File selectedFile =
            fileChooser.getSelectedFile();

    String filePath =
            selectedFile.getAbsolutePath();

    if (!filePath.toLowerCase().endsWith(".pdf")) {

        filePath = filePath + ".pdf";
    }

    try {

        createBillPDF(
                bill,
                filePath
        );

        JOptionPane.showMessageDialog(
                this,
                "Bill downloaded successfully!\n\n"
                + "Location:\n"
                + filePath,
                "Success",
                JOptionPane.INFORMATION_MESSAGE
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Error creating bill PDF:\n"
                + e.getMessage(),
                "PDF Error",
                JOptionPane.ERROR_MESSAGE
        );

        e.printStackTrace();
    }
    }//GEN-LAST:event_btnPrintReceiptActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
       jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_btnHelpActionPerformed

    private void loadDoctors() {
    cmbDentist.removeAllItems();
    cmbDentist.addItem("Select Dentist");
    AppointmentDAO dao = new AppointmentDAO();
    doctorList = dao.getDoctors();
    for (UserModel doctor : doctorList) {
        cmbDentist.addItem(doctor.getName());
    }
}
    
    private void loadAppointments() {

    DefaultTableModel model =
            (DefaultTableModel) tblAppointments.getModel();

    model.setRowCount(0);

    AppointmentDAO dao = new AppointmentDAO();

    ArrayList<AppointmentModel> list =
            dao.getAllAppointments();

    for (AppointmentModel appointment : list) {

        model.addRow(new Object[]{

            appointment.getAppointmentNo(),
            appointment.getPatientName(),
            appointment.getContactNo(),
            appointment.getAddress(),
            appointment.getDentistName(),
            appointment.getAppointmentDate(),
            appointment.getAppointmentTime(),
            appointment.getStatus()
        });
    }
}
    
    private void loadBillAppointmentDetails() {

    AppointmentDAO appointmentDAO =
            new AppointmentDAO();

    AppointmentModel appointment =
            appointmentDAO.getAppointmentByNo(
                    billAppointmentNo
            );

    if (appointment == null) {

        JOptionPane.showMessageDialog(
                this,
                "Appointment not found.",
                "Not Found",
                JOptionPane.ERROR_MESSAGE
        );

        clearBillingDetails();

        return;
    }
     billPatientId =
            appointment.getPatientId();

    
    lblBillPatientID.setText(
            String.valueOf(
                    appointment.getPatientId()
            )
    );
    loadBillTreatments();
    calculateBill();
}
    
    private void calculateBill() {

    grandTotal =
            treatmentTotal + consultationFee;

    lblTreatmentTotal.setText(
            String.format(
                    "Rs. %.2f",
                    treatmentTotal
            )
    );

    lblConsultationFee.setText(
            String.format(
                    "Rs. %.2f",
                    consultationFee
            )
    );

    lblGrandTotal.setText(
            String.format(
                    "Rs. %.2f",
                    grandTotal
            )
    );

    lblBalance.setText("Rs. 0.00");
}
    
    private void displayAppointment(AppointmentModel appointment) {

    txtAppointmentNo.setText(
            String.valueOf(
                    appointment.getAppointmentNo()
            )
    );

    txtPatientName.setText(
            appointment.getPatientName()
    );
    txtContactNum.setText(
            appointment.getContactNo()
    );
    txtAddress.setText(
            appointment.getAddress()
    );
    cmbDentist.setSelectedItem(
            appointment.getDentistName()
    );
    txtDate.setText(
            appointment.getAppointmentDate()
    );
    if (appointment.getAppointmentTime() != null) {
        txtTime.setText(
                appointment.getAppointmentTime()
        );
    } else {
        txtTime.setText("");
    }
    cmbStatus.setSelectedItem(
            appointment.getStatus()
    );
}
    
    private void loadBillTreatments() {

    DefaultTableModel model =
            (DefaultTableModel)
            tblBillTreatments.getModel();

    model.setRowCount(0);

    treatmentTotal = 0.0;

    AppointmentTreatmentDAO dao =
            new AppointmentTreatmentDAO();

    ArrayList<AppointmentTreatmentModel> list =
            dao.getAppointmentTreatments(
                    billAppointmentNo
            );

    for (AppointmentTreatmentModel treatment : list) {

        model.addRow(new Object[]{

            treatment.getTreatmentId(),

            treatment.getTreatmentName(),

            String.format(
                    "%.2f",
                    treatment.getAmount()
            )
        });

        treatmentTotal +=
                treatment.getAmount();
    }
}
    
    private void clearFields() {

    txtName.setText("");
    txtEmail.setText("");
    txtContact.setText("");
    txtPassword.setText("");
    txtConfirmPassword.setText("");

    txtName.requestFocus();
}
    
    private void clearBillingForm() {
    billAppointmentNo = 0;
    treatmentTotal = 0.0;
    grandTotal = 0.0;
    txtBillAppointmentNo.setText("");
    lblBillPatientID.setText("-");
    lblTreatmentTotal.setText("Rs. 0.00");
    lblConsultationFee.setText(
            String.format(
                    "Rs. %.2f",
                    consultationFee
            )
    );

    lblGrandTotal.setText("Rs. 0.00");

    txtPayment.setText("");

    lblBalance.setText("Rs. 0.00");

    DefaultTableModel model =
            (DefaultTableModel)
            tblBillTreatments.getModel();

    model.setRowCount(0);
}
    
    private void loadReceipt(
        int appointmentNo) {

    BillDAO dao =
            new BillDAO();

    BillModel bill =
            dao.getBillByAppointmentNo(
                    appointmentNo
            );

    if (bill == null) {

        JOptionPane.showMessageDialog(
                this,
                "Bill not found."
        );

        return;
    }

    lblReceiptBillId.setText(
            String.valueOf(
                    bill.getBillId()
            )
    );

    lblReceiptAppointmentNo.setText(
            String.valueOf(
                    bill.getAppointmentNo()
            )
    );

    lblReceiptPatientId.setText(
            String.valueOf(
                    bill.getPatientId()
            )
    );

    lblReceiptTreatmentTotal.setText(
            "Rs. "
            + String.format(
                    "%.2f",
                    bill.getTreatmentTotal()
            )
    );

    lblReceiptConsultationFee.setText(
            "Rs. "
            + String.format(
                    "%.2f",
                    bill.getConsultationFee()
            )
    );

    lblReceiptGrandTotal.setText(
            "Rs. "
            + String.format(
                    "%.2f",
                    bill.getGrandTotal()
            )
    );

    lblReceiptPayment.setText(
            "Rs. "
            + String.format(
                    "%.2f",
                    bill.getPayment()
            )
    );

    lblReceiptBalance.setText(
            "Rs. "
            + String.format(
                    "%.2f",
                    bill.getBalance()
            )
    );

    lblReceiptStatus.setText(
            bill.getPaymentStatus()
    );

    lblReceiptDate.setText(
            bill.getBillDate()
    );
}
    
    private void clearBillingDetails() {

    billAppointmentNo = 0;
    treatmentTotal = 0.0;
    grandTotal = 0.0;
    lblBillPatientID.setText("-");
    lblTreatmentTotal.setText("Rs. 0.00");
    lblGrandTotal.setText("Rs. 0.00");
    txtPayment.setText("");
    lblBalance.setText("Rs. 0.00");
    DefaultTableModel model =
            (DefaultTableModel)
            tblBillTreatments.getModel();

    model.setRowCount(0);
}
    private void createBillPDF(
        BillModel bill,
        String filePath) throws IOException {

    PDDocument document =
            new PDDocument();

    try {

        PDPage page =
                new PDPage(PDRectangle.A4);

        document.addPage(page);

        PDPageContentStream content =
                new PDPageContentStream(
                        document,
                        page
                );

        PDType1Font boldFont =
                new PDType1Font(
                        Standard14Fonts.FontName.HELVETICA_BOLD
                );

        PDType1Font normalFont =
                new PDType1Font(
                        Standard14Fonts.FontName.HELVETICA
                );

        float pageWidth =
                page.getMediaBox().getWidth();

        float y = 780;
        content.beginText();

        content.setFont(
                boldFont,
                20
        );

        content.newLineAtOffset(
                180,
                y
        );

        content.showText(
                "SUNRISE DENTAL CLINIC"
        );

        content.endText();


        y -= 25;
        content.beginText();

        content.setFont(
                normalFont,
                11
        );

        content.newLineAtOffset(
                220,
                y
        );

        content.showText(
                "Colombo, Sri Lanka"
        );

        content.endText();


        y -= 40;

        content.beginText();

        content.setFont(
                boldFont,
                16
        );

        content.newLineAtOffset(
                250,
                y
        );

        content.showText(
                "PATIENT BILL"
        );

        content.endText();


        y -= 35;

        content.beginText();

        content.setFont(
                normalFont,
                11
        );

        content.newLineAtOffset(
                70,
                y
        );

        content.showText(
                "Bill ID          : "
                + bill.getBillId()
        );

        content.newLineAtOffset(
                0,
                -20
        );

        content.showText(
                "Appointment No   : "
                + bill.getAppointmentNo()
        );

        content.newLineAtOffset(
                0,
                -20
        );

        content.showText(
                "Patient ID       : "
                + bill.getPatientId()
        );

        content.newLineAtOffset(
                0,
                -20
        );

        content.showText(
                "Bill Date        : "
                + bill.getBillDate()
        );

        content.endText();


        y -= 110;

        content.moveTo(
                70,
                y
        );

        content.lineTo(
                pageWidth - 70,
                y
        );

        content.stroke();


        y -= 30;

        content.beginText();

        content.setFont(
                normalFont,
                12
        );

        content.newLineAtOffset(
                70,
                y
        );

        content.showText(
                "Treatment Total"
        );

        content.newLineAtOffset(
                300,
                0
        );

        content.showText(
                "Rs. "
                + String.format(
                        "%.2f",
                        bill.getTreatmentTotal()
                )
        );

        content.newLineAtOffset(
                -300,
                -25
        );

        content.showText(
                "Consultation Fee"
        );

        content.newLineAtOffset(
                300,
                0
        );

        content.showText(
                "Rs. "
                + String.format(
                        "%.2f",
                        bill.getConsultationFee()
                )
        );

        content.endText();


        y -= 65;

        content.moveTo(
                70,
                y
        );

        content.lineTo(
                pageWidth - 70,
                y
        );

        content.stroke();


        y -= 30;

        content.beginText();

        content.setFont(
                boldFont,
                13
        );

        content.newLineAtOffset(
                70,
                y
        );

        content.showText(
                "GRAND TOTAL"
        );

        content.newLineAtOffset(
                300,
                0
        );

        content.showText(
                "Rs. "
                + String.format(
                        "%.2f",
                        bill.getGrandTotal()
                )
        );

        content.endText();


        y -= 35;
        content.beginText();

        content.setFont(
                normalFont,
                12
        );

        content.newLineAtOffset(
                70,
                y
        );

        content.showText(
                "Payment"
        );

        content.newLineAtOffset(
                300,
                0
        );

        content.showText(
                "Rs. "
                + String.format(
                        "%.2f",
                        bill.getPayment()
                )
        );

        content.newLineAtOffset(
                -300,
                -25
        );

        content.showText(
                "Balance"
        );

        content.newLineAtOffset(
                300,
                0
        );

        content.showText(
                "Rs. "
                + String.format(
                        "%.2f",
                        bill.getBalance()
                )
        );

        content.endText();


        y -= 65;

        content.beginText();

        content.setFont(
                boldFont,
                12
        );

        content.newLineAtOffset(
                70,
                y
        );

        content.showText(
                "Payment Status : "
                + bill.getPaymentStatus()
        );

        content.endText();


        y -= 60;

        content.moveTo(
                70,
                y
        );

        content.lineTo(
                pageWidth - 70,
                y
        );

        content.stroke();


        y -= 35;

        content.beginText();

        content.setFont(
                boldFont,
                12
        );

        content.newLineAtOffset(
                215,
                y
        );

        content.showText(
                "Thank you for visiting!"
        );

        content.endText();


        content.close();

        document.save(filePath);

    } finally {

        document.close();
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToBilling;
    private javax.swing.JButton btnCalculateBalance;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreateBill;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageAppointments;
    private javax.swing.JButton btnPrintReceipt;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSaveBill;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchbill;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbDentist;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelBilling;
    private javax.swing.JPanel jPanelHelp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblBillPatientID;
    private javax.swing.JLabel lblConsultationFee;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JLabel lblReceiptAppointmentNo;
    private javax.swing.JLabel lblReceiptBalance;
    private javax.swing.JLabel lblReceiptBillId;
    private javax.swing.JLabel lblReceiptConsultationFee;
    private javax.swing.JLabel lblReceiptDate;
    private javax.swing.JLabel lblReceiptGrandTotal;
    private javax.swing.JLabel lblReceiptPatientId;
    private javax.swing.JLabel lblReceiptPayment;
    private javax.swing.JLabel lblReceiptStatus;
    private javax.swing.JLabel lblReceiptTreatmentTotal;
    private javax.swing.JLabel lblTreatmentTotal;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTable tblAppointments;
    private javax.swing.JTable tblBillTreatments;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtAppointmentNo;
    private javax.swing.JTextField txtBillAppointmentNo;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtContactNum;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextArea txtHelp;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtPayment;
    private javax.swing.JTextField txtSearchAppointmentNo;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
